config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: :new do 
    collection do
      post :result
    end
  end 
  root 'games#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/game_validatable.rb
# frozen_string_literal: true

# Module to add Game Level Validation
module GameValidatable
  extend ActiveSupport::Concern

  included do
    validates :grid_size, :total_ships, :p1_ships_positions, :p2_ships_positions, :total_missiles, :p1_move_positions,
              :p2_move_positions, presence: true
    validates_format_of :p1_ships_positions, :p2_ships_positions, :p1_move_positions, :p2_move_positions,
                        with: /\A\d,\d(:\d,\d)*\z/, message: 'is not in the correct format'
    validates :grid_size, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
    validate :total_ships, :valid_total_ships
    validate :total_missiles, :valid_total_missiles

    private

    def valid_total_ships
      return if total_ships.is_a?(Numeric) && total_ships.positive? && total_ships <= max_total_ships

      errors.add(:total_ships, "must be a number between 1 and #{max_total_ships}")
    end

    def valid_total_missiles
      return if total_missiles.is_a?(Numeric) && total_missiles.positive? && total_missiles <= max_total_ships

      errors.add(:total_missiles, "must be a number between 1 and #{max_total_ships}")
    end

    def max_total_ships
      (grid_size**2 / 2)
    end
  end
end

app/models/concerns/player_validatable.rb
# frozen_string_literal: true

# Module to add Player Level Validation
module PlayerValidatable
  extend ActiveSupport::Concern

  included do
    validate :max_positions
    validate :input_count

    private

    def max_positions
      {
        p1_ship_positions: player1.ship_positions,
        p1_move_positions: player1.missile_positions,
        p2_ship_positions: player2.ship_positions,
        p2_move_positions: player2.missile_positions
      }.each do |key, values|
        errors.add(key, 'Value Must be inside the matrix size') unless max_value(values)
      end
    end

    def max_value(values)
      values.map { |value| value[0] }.compact.max < (grid_size) && values.map { |value| value[1] }.compact.max < (grid_size)
    end

    def input_count
      {
        p1_ship_positions: player1.ship_positions,
        p2_ship_positions: player2.ship_positions
      }.each do |key, values|
        errors.add(key, 'must equal to total_ships size') unless values.count == total_ships
      end

      {
        p1_move_positions: player1.missile_positions,
        p2_move_positions: player2.missile_positions
      }.each do |key, values|
        errors.add(key, 'must equal to total_missiles size') unless values.count == total_missiles
      end
    end
  end
end

app/models/game.rb
# frozen_string_literal: true

# class to handle the game inputs
class Game
  include ActiveModel::Validations
  include GameValidatable
  include PlayerValidatable

  attr_accessor :grid_size, :total_ships, :p1_ships_positions, :p2_ships_positions, :total_missiles,
                :p1_move_positions, :p2_move_positions

  def initialize(opts = {})
    @grid_size            = opts[:grid_size].to_i
    @total_ships          = opts[:total_ships].to_i
    @p1_ships_positions   = opts[:p1_ships_positions]
    @p2_ships_positions   = opts[:p2_ships_positions]
    @total_missiles       = opts[:total_missiles].to_i
    @p1_move_positions    = opts[:p1_move_positions]
    @p2_move_positions    = opts[:p2_move_positions]
  end

  def player1
    @player1 ||= Player.new(p1_ships_positions, p1_move_positions)
  end

  def player2
    @player2 ||= Player.new(p2_ships_positions, p2_move_positions)
  end
end

app/models/player.rb
# frozen_string_literal: true

# class to handle player's info
class Player
  attr_accessor :ship_positions, :missile_positions

  def initialize(ship_position_str, missile_position_str)
    @ship_positions = ship_position_str.split(':').map { |pos| pos.split(',').map(&:to_i) }
    @missile_positions = missile_position_str.split(':').map { |pos| pos.split(',').map(&:to_i) }
  end

  # method to get ship destroyed ship of player1 by player2's missile.
  def ships_destroyed(player)
    ship_positions & player.missile_positions
  end

  # method to get missile missed by player1 with respect to player2's ships position.
  def missile_missed(player)
    missile_positions - player.ship_positions
  end

  # method to get alived of player1 after attack by player2's missile
  def alived_ships_of(player)
    ship_positions - player.missile_positions
  end
end

app/models/result.rb
# frozen_string_literal: true

# class to calculate the result of the game
class Result
  attr_accessor :grid_size

  def initialize(grid_size)
    @grid_size = grid_size
  end

  def detailed_matrix(player1, player2)
    matrix = []
    (0..(grid_size - 1)).each do |i|
      matrix << (0..(grid_size - 1)).map do |j|
        if player1.ships_destroyed(player2).include?([i, j])
          'X'
        elsif player1.ship_positions.include?([i, j])
          'B'
        elsif player2.missile_positions.include?([i, j])
          'O'
        end
      end
    end
    matrix
  end

  # Always gives results based on the player1 with respec to player2 
  def conclusion(player1, player2)
    ships_destroyed_of_player1 = player1.ships_destroyed(player2)
    ships_destroyed_of_player2 = player2.ships_destroyed(player1)
    if ships_destroyed_of_player1.count > ships_destroyed_of_player2.count
      'Player 2 Wins'
    elsif ships_destroyed_of_player2.count > ships_destroyed_of_player1.count
      'Player 1 Wins'
    else
      "It's Draw"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def result
    @game = Game.new(game_params)
  end

  private

  def game_params
    params.require(:game).permit(
                                  :grid_size, 
                                  :total_ships, 
                                  :p1_ships_positions, 
                                  :p2_ships_positions, 
                                  :total_missiles, 
                                  :p1_move_positions, 
                                  :p2_move_positions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_error.html.erb
<% if @game.errors.any? %>
  <h2>Errors</h2>
  <% @game.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

app/views/games/_result.html.erb
<div class="player">
  <h1> Player <%= id %> </h1>
  <% matrix.each_with_index do |row, i| %>
    <li>
      <ol> 
        <% matrix.each_with_index do |column, j| %>
          <li>
            <span>
              <%= matrix[i][j] %>
            </span>
          </li>
        <% end %>
      </ol>
    </li>
  <% end %>
</div> 

app/views/games/_result_details.html.erb
<div id='result-details'>
  <h1>Result Details</h1>
  <div class="input-div">
    <span class="label">Ship Destroyed of Player 1</span><%= player1.ships_destroyed(player2).count %><span class="label position">Positions</span> <%= player1.ships_destroyed(player2)  %>
  </div>
  <div class="input-div">
    <span class="label">Ship Destroyed of Player 2</span> <%= player2.ships_destroyed(player1).count %><span class="label position">Positions</span><%= player2.ships_destroyed(player1) %>
  </div>
  <div class="input-div">
    <span class="label">Missile Missed of Player 1</span> <%= player2.missile_missed(player1).count %><span class="label position">Positions</span><%= player2.missile_missed(player1) %>
  </div>
    <div class="input-div">
    <span class="label">Missile Missed of Player 2</span> <%= player1.missile_missed(player2).count %><span class="label position">Positions</span><%= player1.missile_missed(player2) %>
  </div>
  <div class="input-div">
    <span class="label">Alived Ship of Player 1</span> <%= player1.alived_ships_of(player2).count %><span class="label position">Positions</span><%= player1.alived_ships_of(player2) %>
  </div>
  <div class="input-div">
    <span class="label">Alived Ship of Player 2</span> <%= player2.alived_ships_of(player1).count %><span class="label position">Positions</span><%= player2.alived_ships_of(player1) %>
  </div>
  <div class="input-div">
    <span class="label">Result</span> <%= result %>
  </div>
</div>

app/views/games/new.html.erb
<div id="game-input">
  <h1> Game of BattleShips </h1>
  <turbo-frame id="error"></turbo-frame>
  <%= form_tag(result_games_path, remote: true) do %>
    <div class="input-div">
      <span class="label">Grid Size</span>
      <%= number_field_tag 'game[grid_size]', nil, required: true, placeholder: 'Size of the battleground [M*M]', max: 10, min: 1 %>
    </div>

    <div class="input-div">
      <span class="label">Total Ships</span>
      <%= number_field_tag 'game[total_ships]', nil, required: true, placeholder: 'Number of ships which can be placed on [M*M]',max: 50, min: 1 %>
    </div>

    <div class="input-div">
      <span class="label">P1 Ship Positions</span>
      <%= text_field_tag 'game[p1_ships_positions]', nil, required: true, placeholder: 'Ship Positions: 1,1:2,0,.. (x,y pairs separated by colon)' %>
    </div>

    <div class="input-div">
      <span class="label">P2 Ship Positions</span>
      <%= text_field_tag 'game[p2_ships_positions]', nil, required: true, placeholder: 'Ship Positions: 1,1:2,0,.. (x,y pairs separated by colon)' %>
    </div>

    <div class="input-div">
      <span class="label">Total Missiles</span>
      <%= number_field_tag 'game[total_missiles]', nil, required: true, placeholder: 'Total number of missiles players have', max: 99, min: 1 %>
    </div>

    <div class="input-div">
      <span class="label">P1 Moves</span>
      <%= text_field_tag 'game[p1_move_positions]', nil, required: true, placeholder: 'Missile Positions: 1,1:2,0,.. (x,y pairs separated by colon)' %>
    </div>

    <div class="input-div">
      <span class="label">P2 Move</span>
      <%= text_field_tag 'game[p2_move_positions]', nil, required: true, placeholder: 'Missile Positions: 1,1:2,0,.. (x,y pairs separated by colon)' %>
    </div>

    <div class="submit-div">
      <%= submit_tag 'Submit', class: 'submit' %>
      <%= link_to 'Reset', root_path, class: 'submit' %>
    </div>  
  <% end %>
  <turbo-frame id="result"></turbo-frame>
</div>

app/views/games/result.turbo_stream.erb
<% unless @game.valid? %>
  <turbo-stream action="update" target="error">
    <template>
      <%= render partial: 'error' %>
    </template>
  </turbo-stream>
<% else %>
  <% result = Result.new(@game.grid_size) %>
  <turbo-stream action="update" target="error">
    <template>
      <%= render partial: 'error' %>
    </template>
  </turbo-stream>
  <turbo-stream action="update" target="result">
    <template>
      <%= render partial: 'result', locals: { id: 1, matrix: result.detailed_matrix(@game.player1, @game.player2) } %>
      <%= render partial: 'result', locals: { id: 2, matrix: result.detailed_matrix(@game.player2, @game.player1) } %>
      <%= render partial: 'result_details', locals: { result: result.conclusion(@game.player1, @game.player2), player1: @game.player1, player2: @game.player2 } %>
    </template>
  </turbo-stream>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BattleshipGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <div id="game-container">
        <%= yield %>
      </div>  
    </main>    
  </body>
</html>